version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php
      - apt-get update
      - apt-get install -y php8.2-cli php8.2-common php8.2-fpm php8.2-mbstring php8.2-curl php8.2-xml
      - apt-get install libsodium-dev
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - npm install -g webpack
  pre_build:
    commands:
      - composer install
      - npm install
  build:
    commands:
      - npm run build
      - composer install --optimize-autoloader --no-dev
artifacts:
  files:
    - "**/*"
  name: TaskApp
proxy:
  upload-artifacts: yes
  logs: yes
