#!/bin/bash
amazon-linux-extras enable php8.2
yum update -y
yum upgrade -y
sudo yum install -y php php-{bcmath,bz2,calendar,core,ctype,curl,date,dba,dom,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,libxml,mbstring,mysqlnd,odbc,openssl,pcntl,pcre,pdo,pdo_mysql,pdo_odbc,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,pspell,random,readline,redis,reflection,session,shmop,simplexml,soap,sockets,spl,sqlite3,standard,tidy,tokenizer,xml,xmlreader,rpc,xmlwriter,xsl,zip,zlib}
yum install -y mariadb-server
yum install -y mod_ssl